import "./globals.css"
import Header from "@/shared/UI/Header/Header";
import Menu from "@/pages/MainPage/UI/Menu/Menu";
import React from "react";
import MainPage from "@/pages/MainPage/MainPage";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Header />
        <Menu />
        <MainPage/>
        </body>
        </html>
    )
}
