import "../globals.css"
import React from "react";
import Layout from "@/shared/Layout/Layout";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <Layout>
                {children}
            </Layout>
        </body>
        </html>
    )
}
